"""empty message

Revision ID: 0b8f4df2205b
Revises:
Create Date: 2023-03-30 22:24:43.129738

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0b8f4df2205b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state", sa.Enum("other", "standard", name="submissiontype"), nullable=True),
        sa.Column("submitted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "submission_history",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("state", sa.Enum("other", "standard", name="submissiontype"), autoincrement=False, nullable=True),
        sa.Column("submitted_date", sa.DateTime(timezone=True), autoincrement=False, nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("version", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("changed", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", "version"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=1000), nullable=True),
        sa.Column("firstname", sa.String(length=1000), nullable=True),
        sa.Column("lastname", sa.String(length=1000), nullable=True),
        sa.Column("middlename", sa.String(length=1000), nullable=True),
        sa.Column("email", sa.String(length=1024), nullable=True),
        sa.Column("sub", sa.String(length=36), nullable=True),
        sa.Column("iss", sa.String(length=1024), nullable=True),
        sa.Column("idp_userid", sa.String(length=256), nullable=True),
        sa.Column("login_source", sa.String(length=200), nullable=True),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sub"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_idp_userid"), ["idp_userid"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_idp_userid"))

    op.drop_table("users")
    op.drop_table("submission_history")
    op.drop_table("submission")
    # ### end Alembic commands ###
