"""empty message

Revision ID: 11dd9c1c87bb
Revises:
Create Date: 2023-03-28 06:59:39.303924

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "11dd9c1c87bb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state", sa.Enum("other", "standard", name="submissiontype"), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "submission_history",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("state", sa.Enum("other", "standard", name="submissiontype"), autoincrement=False, nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("version", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("changed", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", "version"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_user_idp_userid")
        batch_op.drop_constraint("users_idp_userid_key", type_="unique")
        batch_op.create_index(batch_op.f("ix_users_idp_userid"), ["idp_userid"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_idp_userid"))
        batch_op.create_unique_constraint("users_idp_userid_key", ["idp_userid"])
        batch_op.create_index("ix_user_idp_userid", ["idp_userid"], unique=False)

    op.drop_table("submission_history")
    op.drop_table("submission")
    # ### end Alembic commands ###
